# roles/postfix_dumb/tasks/main.yml
---
- name: Postfix_dumb | Install Postfix (Debian)
  apt:
    update_cache: yes
    cache_valid_time: 86400
    install_recommends: no
    name: "{{item}}"
    state: installed
  with_items:
    - postfix
    - libsasl2-modules
    - bsd-mailx
    - ca-certificates
  when: ansible_os_family == "Debian"

- name: Postfix_dumb | Install Postfix (RedHat)
  yum:
    name: "{{item}}"
    update_cache: no
    state: present
  with_items:
    - postfix
    - mailx
    - cyrus-sasl-plain
  when: ansible_os_family == "RedHat"

- name: Postfix_dumb | Set header_checks
  copy:
    src: header_checks
    dest: /etc/postfix
    group: postfix
    owner: postfix
    mode: 0600
  notify:
    - restart postfix

- name: Postfix_dumb | Set main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    group: postfix
    owner: postfix
    mode: 0640
  notify:
    - restart postfix

- name: Postfix_dumb | Ensure postfix owns /etc/postfix
  file:
    path: /etc/postfix
    owner: postfix

- name: Postfix_dumb | Set sasl_passwd
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    group: postfix
    owner: postfix
    mode: 0600
  notify:
    - postmap sasl passwd

- name: Postfix_dumb | Restart Postfix
  service:
    name: postfix
    state: restarted
  when:
    - restart is defined

- name: Postfix_dumb | Set aliases (others)
  lineinfile:
    dest: /etc/aliases
    group: root
    owner: root
    mode: 0644
    line: '{{item.key}}: {{item.value}}'
  when: email_aliases is defined
  with_dict: email_aliases
  notify:
    - execute newaliases
