# roles/postfix_dumb/tasks/main.yml
---
- name: Postfix with external account only | Set header_checks
  copy:
    src: header_checks
    dest: /etc/postfix
    group: postfix
    owner: postfix
    mode: 0600
  notify:
    - restart postfix

- name: Postfix with external account only | Set main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    group: postfix
    owner: postfix
    mode: 0640
  notify:
    - restart postfix

- name: Postfix with external account only | Ensure postfix owns /etc/postfix
  file:
    path: /etc/postfix
    owner: postfix

- name: Postfix with external account only | Set sasl_passwd
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    group: postfix
    owner: postfix
    mode: 0600
  notify:
    - postmap sasl passwd

- name: Postfix with external account only | Restart Postfix
  service:
    name: postfix
    state: restarted
  when:
    - restart is defined

- name: Postfix with external account only | Set aliases (others)
  lineinfile:
    dest: /etc/aliases
    group: root
    owner: root
    mode: 0644
    line: '{{ item.key }}: {{ item.value }}'
    regexp: '{{ item.key }}:'
    state: present
    create: True
  when: postfix_ea_email_aliases is defined
  with_dict: postfix_ea_email_aliases
  notify:
    - execute newaliases
