---
- name: Debian | Install Postfix
  apt:
    update_cache: yes
    cache_valid_time: 86400
    install_recommends: no
    name: "{{item}}"
    state: installed
  with_items:
    - postfix
    - libsasl2-modules
    - bsd-mailx
    - ca-certificates
  when: ansible_os_family == "Debian"

- name: RedHat | Postfix_dumb | Install Postfix
  yum:
    name: "{{item}}"
    update_cache: no
    state: present
  with_items:
    - postfix
    - mailx
    - cyrus-sasl-plain
  when: ansible_os_family == "RedHat"

- name: Set header_checks
  copy:
    src: header_checks
    dest: /etc/postfix
    group: postfix
    owner: postfix
    mode: 0600
  when: postfix_dumb_only_local_accounts
  notify:
    - restart postfix

- name: Set main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    group: postfix
    owner: postfix
    mode: 0640
  notify:
    - restart postfix

- name: Ensure postfix owns /etc/postfix
  file:
    path: /etc/postfix
    owner: postfix

- name: Set sasl_passwd
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    group: postfix
    owner: postfix
    mode: 0600
  notify:
    - postmap sasl passwd

- name: Set aliases
  lineinfile:
    dest: /etc/aliases
    group: root
    owner: root
    mode: '0644'
    line: '{{ item.key }}: {{ item.value }}'
    regexp: '^{{ item.key }}:'
  when: postfix_dumb_email_aliases is defined
  with_dict: '{{ postfix_dumb_email_aliases }}'
  notify:
    - execute newaliases
